FROM centos:6
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Base.repo && \
    sed -i 's|#baseurl=http://mirror.centos.org/centos/$releasever|baseurl=http://vault.centos.org/6.10|g' /etc/yum.repos.d/CentOS-Base.repo && \
    yum update -y && yum install -y httpd mod_ssl

EXPOSE 80 443
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
